name: nihaixia_app
description: 倪海厦中医离线问答
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  http: ^1.2.0
  llama_cpp_dart:
    path: third_party/llama_cpp_dart
  flutter_markdown: ^0.7.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

hooks:
  user_defines:
    sqlite3:
      source: sqlite3
      url_pattern: "https://ghfast.top/https://github.com/simolus3/sqlite3.dart/releases/download/$RELEASE_TAG/$FILENAME"

flutter:
  uses-material-design: true
  assets:
    - assets/kb/kb.sqlite3
    - assets/models/Qwen3.5-0.8B-Q6_K.gguf
